### PR TITLE
Add dispatch bindings

### PR DESCRIPTION
**Pull request by samoht**
This is my first test of exporting bindings using `camlkit-bindings-generator`. I probably have missed a few things. I'm also not sure `OS_*` symbols are supposed to be exposed like this..

Note that I haven't tried to use those bindings yet 😅

### CODE REVIEW

**Comment by dboris** [comment]
I think this library will be tricky to bind and will probably need another tool or a different approach. I'll give it some more thought.

**Comment by dboris** [comment]
As I see it, another tool can come in handy here. Library metadata for libdispatch has been created by the PyObjC project in [JSON format](https://github.com/ronaldoussoren/pyobjc/blob/master/pyobjc-framework-libdispatch/metadata/dispatch.fwinfo). We could use it as a starting point and either emit ctypes bindings after parsing it, or convert it to XML in the BridgeSupport schema, so it would work like this:
```sh
cat dispatch.fwinfo | fwinfo-to-bs | bs-to-ml > Dispatch_globals.ml
```

**Comment by dboris** [comment]
I managed to generate a BridgeSupport file and globals bindings. 

The key is in `man gen_bridge_metadata`:
```
     It is also possible to generate bridge support metadata for a standalone C library
     (here, libcurl):
           gen_bridge_metadata -c '-lcurl -I/usr/include/curl' /usr/include/curl/*.h >
           /Library/BridgeSupport/curl.bridgesupport
```

See https://github.com/dboris/camlkit/blob/main/dispatch/dispatch_globals.ml

**Comment by samoht** [comment]
That's really great, thanks! I'm closing this PR as 7ba8dc34534a8a8c8773090c933e676fe4bd5239 is much better

**Pull request closed without merging**
